### ISSUE TITLE
Wald statistic for the high-dimensional Granger causality tests

### ISSUE THREAD

**Issue by analytics-bootcamp** [jstriaukas/midasml#3]
In paragraph 2.4 of "High-Dimensional Granger Causality Tests with an Application to VIX and News", a null hypothesis is tested. Is the Wald statistic discussed on the same page available in midas-ml?

**Comment by jstriaukas** [comment]
midasml package currently does not have the Granger causality testing - it is only for predictive appplications. We have, nonetheless, a plan to make the Granger causality test available in the near future. I will post here a comment once it is available.
