### ISSUE TITLE
midasml Tutorial

### ISSUE THREAD

**Issue by JRatschat** [jstriaukas/midasml#5]
Hi,

I am interested in applying this approach to one of my research papers. Sadly, I have not found a tutorial on how to use your package. Is there any example code/project available that I could use to understand better how to apply your R code?

Thank you very much!

Best,
Jonathan

**Comment by jstriaukas** [comment]
Dear Jonathan,

Thanks for the interest in our method. We don't yet have an example code/vignette of the package. Each function of the package is described quite well, see https://cran.r-project.org/web/packages/midasml/midasml.pdf

Also, our paper describes in detail how to apply our method (see also appendix): https://doi.org/10.1080/07350015.2021.1899933.

Hope this helps at least to start. Further questions or suggestions are welcome. 

Best,
Jonas
