### ISSUE TITLE
sglfitF convergence 

### ISSUE THREAD

**Issue by jstriaukas** [jstriaukas/midasml#7]
Fix: prox_sgl - stop after a certain number of iterations, return the non-convergence flag. 
comment: if the min problem is non-converging (e.g. data irregularities) prox_sgl will not escape the loop. 

Fix: sglfit - add data check-ups. 
comment: if y,x has NA, Inf, stop. if y,x has large outliers, report a warning.

**Comment by neithen-Lu** [comment]
> Fix: prox_sgl - stop after a certain number of iterations, return the non-convergence flag. comment: if the min problem is non-converging (e.g. data irregularities) prox_sgl will not escape the loop.
> 
> Fix: sglfit - add data check-ups. comment: if y,x has NA, Inf, stop. if y,x has large outliers, report a warning.

Thanks for your immediate response and help!

**Comment by jstriaukas** [comment]
solved.

**Comment by jstriaukas** [comment]
a
